# alacritty.toml
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations     = "Full"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Windowed"
#startup_mode    = "SimpleFullscreen"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 12
y = 12

[scrolling]
history = 12000

[font]
builtin_box_drawing = true
size                = 13

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "RobotoMono Nerd Font"
#family = "MesloLGS NF"
#family = "Inconsolata Nerd Font Mono"
style  = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
#family = "MesloLGS NF"
#family = "Inconsolata Nerd Font Mono"
style  = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
#family = "MesloLGS NF"
#family = "Inconsolata Nerd Font Mono"
style  = "Italic"

[font.normal]
#family = "MesloLGS NF"
#family = "Inconsolata Nerd Font Mono"
family = "RobotoMono Nerd Font"
style  = "Regular"


[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
